### PR TITLE
Upgrade to latest version of kubebuilder

### PR DESCRIPTION
**Pull request by dethi**
- Stop using operator-sdk, as we don't use any of the additional feature and it makes it harder to upgrade
- Switch to [go/v4 plugin](https://book.kubebuilder.io/migration/v3vsv4#tldr-of-the-new-gov4-plugin): this change a bit the layout of the project. go/v4 is the only supported version and ensure that we will support newer version of Go and Kubernetes.
- Enabling the pprof endpoint is now directly part of the manager
- Namespace cannot be specified anymore. This makes the controller watch for the CRD in all namespaces. Future changes are needed to support managing multiple clusters from the same controller.
- Upgrade gohbase to the latest version available.

### CODE REVIEW

**Comment by pidren** [comment]
> Namespace cannot be specified anymore. This makes the controller watch for the CRD in all namespaces.

Why are we even upgrading then?

**Comment by dethi** [comment]
As for why upgrading:
- kubebuilder and controller-runtime generally only support a specific version of Go, in that case the previous version was not supporting Go >1.19. This meant that there are dependencies I couldn't even upgrade.
- They also support a set of Kubernetes version. If you want to be able to use newer feature of Kubernetes, you have to upgrade to newer version.
- etc

ABU

**Comment by pidren** [comment]
Let me clarify my point:

> This makes the controller watch for the CRD in all namespaces.

This will not work on the larger production clusters. It's inherently a worse setup than what we have today.

**Comment by dethi** [comment]
Having the operator watch for its own CRD in one namespace or all namespaces ultimately shouldn't change anything, since it is still watching only its own CRD type and that type is still only used in one place and still has only one instance

**Comment by dethi** [comment]
That being said, I added back the flag (the option has moved in the manager to the cache). This way it can be enabled/disabled like before. And multi instance of the CRD setup is not something that works today anyway, but something I may address in a follow-up PR.

**Review by pidren — APPROVED** [review]

**Pull request merged**
